
title: DieuDTQ Profile
url: 'https://dieudtq.github.io'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Đỗ Trung Quang Diệu  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Da Nang, Viet Nam


## Social Profiles
facebook: http://www.facebook.com/dieudtq.gun  ## your facebook account url
# twitter: http://www.twitter.com  ## your twitter account url
# linkedin: http://www.linkedin.com  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
